spring.application.name=news_perception
server.port=8080

# LangChain4j OpenAI配置
#langchain4j.open-ai.api-key=sk-1385614cbbf54c78a55c7c9d93632496
#langchain4j.open-ai.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
#langchain4j.open-ai.model-name=qwen-max
#langchain4j.open-ai.temperature=0.9

langchain4j.open-ai.api-key=sk-b14c6a5de0e9911d467cdcd6d3df6029
langchain4j.open-ai.base-url=https://apis.iflow.cn/v1
langchain4j.open-ai.model-name=iflow-rome-30ba3b
langchain4j.open-ai.temperature=0.5

# Thymeleaf配置
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://111.228.34.65:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
logging.level.com.qr.np.mapper=debug

